apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pepsico-rest-call
  title: Pepsico Rest 1.0
  description: The Pepsico Rest
  tags:
    - rest
    - pepsi
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Provide Dev Flow Variables 
      required:
        - approvalcode
      properties:
        approvalcode:
          title: Service Now Approval Code
          type: string 


  
  steps:
#  - id: backstage_request
#    name: backstage request
#    action: http:backstage:request
#    input:
#      method: 'GET'
#      path: 'https://api.thecatapi.com/v1/images/0XYvRd7oD'
#      headers:
#        content-type: 'application/json'


    - id: restpepsi
      name: Call our SpringBoot Rest Service
      action: http:backstage:request
      input:
        method: 'POST'
        path: 'https://test-app-2099-dev-test-app-2099-dev.apps.cluster-qmdjh.qmdjh.sandbox1439.opentlc.com/api/hello'
        headers:
            test: 'hello'
            foo: 'bar'
        body:
            name: 'test'
            bar: 'foo'
      
output:
  getResponse: '{{ steps.restpepsi.output.body }}'
  getCode: '{{ steps.restpepsi.output.code }}'
  getHeaders: '{{ steps.restpepsi.output.headers }}'
