apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: rest 
  title: Pepsico Rest
  description: The Pepsico Rest
  tags:
    - rest
    - pepsi
spec:
  owner: rhdh
  type: service
  
  
steps:
  - id: backstage_request
    name: backstage request
    action: http:backstage:request
    input:
      method: 'GET'
      path: 'https://api.thecatapi.com/v1/images/0XYvRd7oD'
      headers:
        test: 'hello'
        foo: 'bar'


output:
  getResponse: '{{ steps.backstage_request.output.body }}'
  getCode: '{{ steps.backstage_request.output.code }}'
  getHeaders: '{{ steps.backstage_request.output.headers }}'
