apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pepsico-rest-call
  title: Pepsico Rest 1.6
  description: The Pepsico Rest
  tags:
    - rest
    - pepsi
spec:
  owner: rhdh
  type: service
  

  
  steps:
#  - id: backstage_request
#    name: backstage request
#    action: http:backstage:request
#    input:
#      method: 'GET'
#      path: 'https://api.thecatapi.com/v1/images/0XYvRd7oD'
#      headers:
#        content-type: 'application/json'


    - id: restpepsi
      name: Call our SpringBoot Rest Service
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/pepsico-service'
        
      
  output:
    getResponse: '{{ steps["restpepsi"].output.body }}'
    getCode: '{{ steps["restpepsi"].output.code }}'
    getHeaders: '{{ steps["restpepsi"].output.headers }}'
