apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pepsico-rest-call
  title: Pepsico Rest 2.5
  description: The Pepsico Rest
  tags:
    - rest
    - pepsi
spec:
  owner: rhdh
  type: service
  

  
  steps:
#  - id: backstage_request
#    name: backstage request
#    action: http:backstage:request
#    input:
#      method: 'GET'
#      path: 'https://api.thecatapi.com/v1/images/0XYvRd7oD'
#      headers:
#        content-type: 'application/json'


    - id: restpepsi
      name: Call our SpringBoot Rest Service
      action: http:backstage:request
      input:
        method: 'GET'
        path: 'proxy/pepsico-service/api/hello'

    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: the code ${{ steps.restpepsi.output.code }}
       
        
      
  output:
    text: 
    - title: REST content
      content: |
        The info: 
        - ResponseObject: ${{ steps.restpepsi.output.body | dump }}
        - ResponseCode: ${{ steps.restpepsi.output.code }}
        - ResponseHeaders: ${{ steps.restpepsi.output.headers | dump }}



 
