apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: rest test
  title: Pepsico REST 1.0
  description: Just a REST TEST
  tags:
    - rest
spec:
  owner: rhdh
  type: service
  



# Edit the template parameters below to see how they will render in the scaffolder form UI
parameters:
  - title: pepsico-rest
    required:
      - name
    properties:
      name:
        title: cats
        type: string
        description: type of cat
      
  
steps:
  - id: backstage_request
    name: Fetch Cats
    action: http:backstage:request
    input:
      path: https://api.thecatapi.com/v1/images/0XYvRd7oD
      method: 'GET'
      headers:
          test: 'hello'
          foo: 'bar'

  - id: debug-cats
    name: Debug Cats
    action: debug:log
    input: 
      message: 'test here'
      
output:
  getResponse: '{{ steps.backstage_request.output.body }}'
  getCode: '{{ steps.backstage_request.output.code }}'
  getHeaders: '{{ steps.backstage_request.output.headers }}'
