apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pepsico service call
  title: Pepsico Rest
  description: The Pepsico Rest
  tags:
    - rest
    - pepsi
spec:
  owner: rhdh
  type: service




  
steps:
  - id: backstage_request
    name: backstage request
    action: http:backstage:request
    input:
      method: POST
      path: https://api.thecatapi.com/v1/images/0XYvRd7oD
      

output:
  getResponse: '{{ steps.backstage_request.output.body }}'
  getCode: '{{ steps.backstage_request.output.code }}'
  getHeaders: '{{ steps.backstage_request.output.headers }}'
