apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pepsico service call 1.0
  title: Pepsico Rest
  description: The Pepsico Rest
  tags:
    - rest
    - pepsi
spec:
  owner: rhdh
  type: service




  
steps:
  - id: backstage_request
    name: backstage request
    action: http:backstage:request
    input:
      method: 'GET'
      path: 'https://api.thecatapi.com/v1/images/0XYvRd7oD'
      headers:
        content-type: 'application/json'
      

output:
  getResponse: '{{ steps.backstage_request.output.body }}'
  getCode: '{{ steps.backstage_request.output.code }}'
  getHeaders: '{{ steps.backstage_request.output.headers }}'
