apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pepsico-rest-call
  title: Pepsico Rest 2.7
  description: The Pepsico Rest
  tags:
    - rest
    - pepsi
spec:
  owner: rhdh
  type: service
  

  
  steps:
#  - id: backstage_request
#    name: backstage request
#    action: http:backstage:request
#    input:
#      method: 'GET'
#      path: 'https://api.thecatapi.com/v1/images/0XYvRd7oD'
#      headers:
#        content-type: 'application/json'


    - id: restspringboot
      name: Call our Internal to Openshift Rest Service created in DevHub
      action: http:backstage:request
      input:
        method: 'GET'
        path: 'proxy/pepsico-service/api/hello'

    

    

    - id: restexternal
      name: Call an External REST Call (Public Cats Service)
      action: http:backstage:request
      input:
        method: 'GET'
        path: 'proxy/cats-service/v1/images/0XYvRd7oD'
       
        
      
  output:
    text: 
    - title: REST Internal to OCP Example Response
      content: |
        The Raw Data: 
        - ResponseBody: ${{ steps.restspringboot.output.body | dump }}
        - ResponseCode: ${{ steps.restspringboot.output.code }}
        - ResponseHeaders: ${{ steps.restspringboot.output.headers | dump }}
    text: 
    - title: REST External Cats Service Example Response
      content: |
        The Raw Data: 
        - ResponseBody: ${{ steps.restexternal.output.body | dump }}
        - ResponseCode: ${{ steps.restexternal.output.code }}
        - ResponseHeaders: ${{ steps.restexternal.output.headers | dump }}




 
